import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { cn } from "@/src/shared/lib/utils";
import { Header } from "@/src/components/Header";
import { Providers } from "@/src/providers/Providers";

import "../../shared/styles/globals.css";
import { Footer } from "@/src/components/Footer";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const SITE_NAME = "Дипломный проект";

export const metadata: Metadata = {
  title: {
    absolute: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={cn("h-full", "antialiased", "font-sans", roboto.variable)}
      suppressHydrationWarning
    >
      <body className="bg-accent">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
